#ifndef PACKETTYPESH
#define PACKETTYPESH
namespace ZeldaOnline {

enum ClientPackets {
    CLIENT_PACKET_AUTH = 0,
    CLIENT_PACKET_UPDATE_PLAYER = 1,
    CLIENT_PACKET_REQUEST_ACTOR_SPAWN = 2,
    CLIENT_PACKET_REQUEST_ACTOR_SPAWN_AS_CHILD = 3,
    CLIENT_PACKET_ACTOR_SPAWN_AS_CHILD = 4,
    CLIENT_PACKET_SET_ROOM_SCENE = 5,
    CLIENT_PACKET_UPDATE_ACTOR = 6,
    CLIENT_PACKET_ACTOR_DIED = 7,
    CLIENT_PACKET_ACTOR_TRIGGER_TO_PUPPETS = 8,
    CLIENT_PACKET_ACTOR_TRIGGER_TO_LEADER = 9,
    CLIENT_PACKET_UPDATE_APPEARANCE = 10,
    CLIENT_PACKET_CLAIM_ACTOR = 11,
    CLIENT_PACKET_SCENE_FLAG = 12,
    CLIENT_PACKET_SCENE_TRIGGER = 13,

    CLIENT_PACKET_RELINQUISH_ACTOR_LEADER = 14,
    CLIENT_PACKET_SETUP_ACTORS_DONE = 15,
    CLIENT_PACKET_SET_PARTY = 16,
    CLIENT_PACKET_RELEASE_ROOM = 17,
    CLIENT_PACKET_ACTOR_PROPERTIES = 18,
    CLIENT_PACKET_SET_ACTOR_LOCKED = 19,

    CLIENT_PACKET_ACTOR_SPAWN = 20,
    CLIENT_PACKET_ACTOR_SOUND = 21,
    CLIENT_PACKET_OCARINA_SFX = 22,
    CLIENT_PACKET_SET_PAUSE_STATE = 23,
    CLIENT_PACKET_DECLINE_ACTOR_LEADER = 24,

};

enum ServerPackets {
    SERVER_PACKET_UPDATE_PLAYER = 0,
    SERVER_PACKET_ACTOR_SPAWN = 1,
    SERVER_PACKET_ACTOR_SPAWN_AS_CHILD = 2,
    SERVER_PACKET_UPDATE_ACTOR = 4,
    SERVER_PACKET_DESTROY_ACTOR = 5,
    SERVER_PACKET_AUTH_RESPONSE = 6,
    SERVER_PACKET_ACTOR_TRIGGER = 7,
    SERVER_PACKET_UPDATE_APPEARANCE = 8,
    SERVER_PACKET_SET_ACTOR_LEADER = 9,
    SERVER_PACKET_SCENE_FLAG = 10,
    SERVER_PACKET_WORLD_TIME = 11,
    SERVER_PACKET_SCENE_TRIGGER = 12,
    SERVER_PACKET_ROOM_TEMP_FLAGS = 13,
    SERVER_PACKET_ACTOR_PROPERTIES = 14,
    SERVER_PACKET_SET_ACTOR_LOCKED = 15,

    SERVER_PACKET_ASSIGN_ACTOR_ID = 16,
    SERVER_PACKET_ACTOR_SOUND = 17,
    SERVER_PACKET_OCARINA_SFX = 18,
    SERVER_PACKET_DAMAGE_PLAYER = 19,
    SERVER_PACKET_ROOM_LOADED = 20,
};

static const int PLAYER_PUPPET_ROOM = -1;

static const char SCENE_SCOPED_ROOM = -1;

inline bool IsPartyScene(int sceneNum) {
    return sceneNum <= 0x19 && sceneNum != 0x10;
}

inline uint32_t MakeSceneKey(int sceneNum, int isFuture, int otherVariant) {
    return ((uint32_t)(sceneNum & 0x7FFF)) | ((uint32_t)(isFuture & 0x1) << 15) |
           ((uint32_t)(otherVariant & 0xFFFF) << 16);
}

inline uint64_t MakeServerSceneKey(uint32_t sceneKey, uint32_t partyHash) {
    return (uint64_t)sceneKey | ((uint64_t)partyHash << 32);
}
}

#endif
